Repository sou-so/Souso_Client, pull requests merged in 2022-10, with the labels that each got.

#1 🎉 프로젝트 초기 세팅 (prettier / 절대경로)
  .prettierrc
  jsconfig.json
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/MainPage.js
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/GlobalStyles.js
Labels: enhancement

#2 ✨ setting router
  package-lock.json
  package.json
  src/App.js
  src/index.js
  src/pages/JoinPage.js
  src/pages/LoginPage.js
  src/pages/MainPage.js
  src/pages/index.js
Labels: enhancement

#3 💄 Noto Sans 폰트, ThemeProvider 및 모바일 레이아웃 추가
  public/index.html
  src/App.js
  src/index.js
  src/pages/JoinPage/JoinPage.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/MainPage/MainPage.jsx
  src/pages/index.js
  src/styles/GlobalStyles.js
  src/styles/Theme.js
Labels: style 💄

#6 ♻ 로그인 페이지 UI 수정
  src/App.js
  src/components/Login/LoginForm/LoginForm.jsx
  src/components/Login/LoginForm/styles.js
  src/pages/IntroPage/IntroPage.jsx
  src/pages/IntroPage/styles.js
  src/pages/LoginPage/LoginPage.jsx
  src/pages/LoginPage/styles.js
  src/pages/MainPage/MainPage.jsx
  src/pages/index.js
  src/styles/GlobalStyles.js
  src/styles/Shared.js
  src/styles/Theme.js
Labels: refactor ♻
