Repository sou-so/Souso_Client, pull requests merged in 2022-12, with the labels that each got.

#34 ✨ 댓글 삭제 기능 api 구현 & 회원가입완료 및 서비스 준비중 페이지 UI생성
  src/App.js
  src/api/queries/comment/endpoint.js
  src/api/queries/comment/index.js
  src/assets/icons/arrow_white.svg
  src/assets/icons/pencil_writing.svg
  src/assets/images/incomplete_logo.png
  src/assets/images/welcome.png
  src/components/AppLayout/AppLayout.jsx
  src/components/Common/EditDeleteButton/EditDeleteButton.jsx
  src/components/Common/EditDeleteButton/styles.js
  src/components/Common/Navbar/Navbar.jsx
  src/components/Common/index.js
  src/components/Feed/PostList/PostList.jsx
  src/components/FeedView/Comments/CommentBody/CommentBody.jsx
  src/components/FeedView/Comments/CommentContents/CommentContents.jsx
  src/components/FeedView/Comments/CommentContents/styles.js
  src/components/FeedView/Comments/CommentForm/CommentForm.jsx
  src/components/MyPage/LogoutButton/LogoutButton.jsx
  src/components/MySubPage/MyComments/MyComments.jsx
  src/components/MySubPage/MyPosts/MyPosts.jsx
  src/components/MySubPage/index.js
  src/pages/FeedAddPage/FeedAddPage.jsx
  src/pages/FeedListPage/FeedListPage.jsx
  src/pages/FeedPage/FeedPage.jsx
  src/pages/FeedPage/styles.js
  src/pages/FeedViewPage/FeedViewPage.jsx
  src/pages/IncompletePage/IncompletePage.jsx
  src/pages/IncompletePage/styles.js
  src/pages/JoinPage/JoinPage.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/WelcomePage/WelcomePage.jsx
  src/pages/WelcomePage/styles.js
  src/pages/index.js
Labels: new feature ✨

#35 ✨ 회원가입 email 중복체크 API 연결
  src/api/queries/join/endpoint.js
  src/api/queries/join/index.js
  src/components/Join/InputEmailCheck/InputEmailCheck.jsx
  src/components/Join/JoinForm/JoinForm.jsx
  src/components/Join/index.js
Labels: new feature ✨

#36 💄 favicon 및 카테고리 리스트 Icon 추가
  public/favicon.ico
  public/index.html
  src/assets/icons/category/bulb.svg
  src/assets/icons/category/clock.svg
  src/assets/icons/category/fire.svg
  src/assets/icons/category/lightning.svg
  src/assets/icons/category/lost.svg
  src/assets/icons/category/map.svg
  src/assets/icons/category/puzzle.svg
  src/assets/icons/category/question_circle.svg
  src/components/Common/Category/Category.jsx
  src/components/Common/Category/styles.js
  src/components/Common/Icon/Icon.jsx
  src/components/FeedAdd/SelectedCategory/SelectedCategory.jsx
  src/pages/FeedAddPage/FeedAddPage.jsx
Labels: style 💄

#38 ✨ 커스텀 Alert 라이브러리 추가 & 프로필 수정 API 연결
  package-lock.json
  package.json
  src/App.js
  src/api/queries/user/index.js
  src/components/Common/FetchObserver/FetchObserver.jsx
  src/components/Feed/FeedHeader/FeedHeader.jsx
  src/components/FeedAdd/FeedForm/FeedForm.jsx
  src/components/FeedView/Comments/CommentContents/CommentContents.jsx
  src/components/FeedView/Comments/CommentForm/CommentForm.jsx
  src/components/FeedView/ImageSlider/styles.js
  src/components/Join/InputBirthDate/InputBirthDate.jsx
  src/components/Join/InputBirthDate/styles.js
  src/components/Join/InputVerified/InputVerified.jsx
  src/components/Join/JoinForm/JoinForm.jsx
  src/components/Join/JoinForm/styles.js
  src/components/MyPage/ComingMeetup/ComingMeetup.jsx
  src/components/MyPage/ComingMeetup/styles.js
  src/components/MyPage/LogoutButton/LogoutButton.jsx
  src/components/MySubPage/MyPosts/MyPosts.jsx
  src/components/Post/PostBodyUser/PostBodyUser.jsx
  src/components/ProfileEdit/EditImage/EditImage.jsx
  src/components/ProfileEdit/ProfileForm/ProfileForm.jsx
  src/components/TownAuth/SubmitModal/SubmitModal.jsx
  src/data/comingmeets.json
  src/hooks/useForm.js
  src/pages/FeedAddPage/FeedAddPage.jsx
  src/pages/JoinPage/JoinPage.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/ProfileEditPage/ProfileEditPage.jsx
  src/pages/WelcomePage/WelcomePage.jsx
  src/pages/WelcomePage/styles.js
  src/styles/GlobalStyles.js
  src/styles/Theme.js
  src/utils/dateConverter.js
  src/utils/valid_join.js
Labels: new feature ✨

#39 ✨ 프로필 정보 수정 API 연결
  src/api/queries/user/index.js
  src/components/ProfileEdit/EditImage/EditImage.jsx
  src/components/ProfileEdit/ProfileForm/ProfileForm.jsx
  src/pages/ProfileEditPage/ProfileEditPage.jsx
Labels: new feature ✨

#40 💄 인증코드 재발송 타이머 생성 및 JoinPage의 component UI 일부 수정
  src/components/Join/Input/styles.js
  src/components/Join/InputBirthDate/InputBirthDate.jsx
  src/components/Join/InputVerified/InputVerified.jsx
  src/components/Join/InputVerified/Timer.jsx
  src/components/Join/TermsModal/TermsContents.jsx
  src/components/Join/TermsModal/TermsModal.jsx
  src/components/Join/TermsModal/styles.js
  src/utils/dateConverter.js
Labels: style 💄

#41 ✨ 프로필 이미지 초기화 버튼 생성 및 api 코드 수정
  src/components/ProfileEdit/EditImage/EditImage.jsx
  src/components/ProfileEdit/EditImage/styles.js
  src/components/ProfileEdit/ImgResetBtn/ImgResetBtn.jsx
  src/components/ProfileEdit/ImgResetBtn/styles.js
  src/components/ProfileEdit/ProfileForm/ProfileForm.jsx
  src/components/ProfileEdit/index.js
Labels: new feature ✨

#42 ♻ 회원가입 validate 함수 수정 & 비밀번호 표시/숨기기 구현
  src/api/queries/join/endpoint.js
  src/assets/icons/eye_off.svg
  src/assets/icons/eye_on.svg
  src/components/Common/Icon/Icon.jsx
  src/components/FeedView/Comments/CommentContents/CommentContents.jsx
  src/components/FeedView/Comments/CommentForm/CommentForm.jsx
  src/components/Join/Input/Input.jsx
  src/components/Join/Input/styles.js
  src/components/Join/InputDuplicated/InputDuplicated.jsx
  src/components/Join/InputEmailCheck/InputEmailCheck.jsx
  src/components/Join/InputPassword/InputPassword.jsx
  src/components/Join/InputVerified/InputVerified.jsx
  src/components/Join/JoinForm/JoinForm.jsx
  src/components/Join/JoinForm/styles.js
  src/components/Join/TermsModal/styles.js
  src/components/Join/index.js
  src/components/MyPage/LogoutButton/LogoutButton.jsx
  src/components/MySubPage/CategoryTab/CategoryTab.jsx
  src/components/MySubPage/MyPosts/MyPosts.jsx
  src/components/Post/PostFooterBtn/PostFooterBtn.jsx
  src/components/TownAuth/NeighborList/NeighborList.jsx
  src/components/TownAuth/SearchBar/SearchBar.jsx
  src/components/TownAuth/SearchModal/SearchModal.jsx
  src/components/TownAuth/SearchModal/styles.js
  src/components/TownAuth/SubmitModal/SubmitModal.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/LoginPage/styles.js
  src/styles/GlobalStyles.js
  src/utils/valid_join.js
Labels: refactor ♻

#43 ✨ kakao 지도 API에서 현재 위치 주소 가져오기
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/Feed/FeedHeader/FeedHeader.jsx
  src/components/Join/JoinForm/JoinForm.jsx
  src/components/MyPage/UserData/UserData.jsx
  src/components/Post/PostBodyUser/PostBodyUser.jsx
  src/components/ProfileEdit/ProfileForm/ProfileForm.jsx
  src/components/TownAuth/NeighborList/NeighborList.jsx
  src/components/TownAuth/NeighborList/styles.js
  src/components/TownAuth/SearchModal/SearchModal.jsx
  src/components/TownAuth/SearchModal/styles.js
  src/components/TownAuth/SubmitModal/SubmitModal.jsx
  src/components/TownAuth/SubmitModal/styles.js
  src/index.js
  src/pages/TownAuthPage/TownAuthPage.jsx
  src/recoil/atom.js
Labels: new feature ✨

#44 💄 메인페이지 탭바 스타일 수정 & 그외 버튼, 카테고리 색상 수정
  src/atoms/town.js
  src/components/Common/Category/Category.jsx
  src/components/Common/Category/styles.js
  src/components/Common/Navbar/styles.js
  src/components/Feed/FeedAddButton/styles.js
  src/components/Feed/PostList/PostList.jsx
  src/components/Feed/PostList/styles.js
  src/components/ProfileEdit/ImgResetBtn/styles.js
  src/components/TownAuth/NeighborList/NeighborList.jsx
  src/components/TownAuth/SubmitModal/SubmitModal.jsx
  src/pages/FeedPage/styles.js
  src/pages/TownAuthPage/TownAuthPage.jsx
Labels: style 💄

#45 ♻️ 동네 인증 데이터 서버에 저장 및 불러오기
  src/api/queries/user/endpoint.js
  src/api/queries/user/index.js
  src/atoms/address.js
  src/atoms/town.js
  src/components/Feed/FeedBanner/FeedBanner.jsx
  src/components/Feed/FeedHeader/FeedHeader.jsx
  src/components/Feed/PostList/styles.js
  src/components/Join/JoinForm/JoinForm.jsx
  src/components/MyPage/UserData/UserData.jsx
  src/components/Post/PostBodyUser/PostBodyUser.jsx
  src/components/ProfileEdit/ProfileForm/ProfileForm.jsx
  src/components/TownAuth/KakaoMap/KakaoMap.jsx
  src/components/TownAuth/KakaoMap/styles.js
  src/components/TownAuth/NeighborList/NeighborList.jsx
  src/components/TownAuth/SearchSection/SearchSection.jsx
  src/components/TownAuth/SearchSection/styles.js
  src/components/TownAuth/SubmitModal/SubmitModal.jsx
  src/components/TownAuth/index.js
  src/pages/FeedPage/FeedPage.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/TownAuthPage/TownAuthPage.jsx
  src/pages/TownAuthPage/styles.js
Labels: refactor ♻

#48 ♻ 게시글의 User 헤더와 댓글 User 헤더를 공통 컴포넌트로 수정
  src/components/Common/Skeleton/SkeletonThBottom.jsx
  src/components/Common/UserHeader/UserHeader.jsx
  src/components/Common/UserHeader/styles.js
  src/components/Common/index.js
  src/components/FeedView/Comments/CommentBody/styles.js
  src/components/FeedView/Comments/CommentContents/CommentContents.jsx
  src/components/FeedView/Comments/CommentContents/styles.js
  src/components/FeedView/Comments/CommentForm/CommentForm.jsx
  src/components/FeedView/Comments/CommentForm/styles.js
  src/components/FeedView/Comments/ReplyForm/ReplyForm.jsx
  src/components/FeedView/Comments/ReplyForm/styles.js
  src/components/MySubPage/MyPosts/MyPosts.jsx
  src/components/Post/PostBodyUser/PostBodyUser.jsx
  src/components/Post/PostBodyUser/styles.js
  src/pages/FeedAddPage/FeedAddPage.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/ProfileEditPage/ProfileEditPage.jsx
  src/utils/valid_join.js
Labels: refactor ♻

#49 💄 CommentHeader 컴포넌트 분리 및 스타일 수정
  src/components/Common/EditDeleteButton/EditDeleteButton.jsx
  src/components/Common/LabelTag/LabelTag.jsx
  src/components/Common/UserHeader/UserHeader.jsx
  src/components/Common/index.js
  src/components/FeedView/Comments/CommentContents/CommentContents.jsx
  src/components/FeedView/Comments/CommentContents/styles.js
  src/components/FeedView/Comments/CommentForm/CommentForm.jsx
  src/components/FeedView/Comments/CommentForm/styles.js
  src/components/FeedView/Comments/CommentHeader/CommentHeader.jsx
  src/components/FeedView/Comments/CommentHeader/styles.js
  src/components/FeedView/Comments/EditForm/EditForm.jsx
  src/components/FeedView/Comments/EditForm/styles.js
  src/components/FeedView/Comments/ReplyForm/ReplyForm.jsx
  src/components/FeedView/Comments/ReplyForm/styles.js
  src/components/FeedView/index.js
  src/components/MySubPage/MyComments/MyComments.jsx
  src/components/MySubPage/MyMeets/MyMeets.jsx
  src/components/Post/PostBody/PostBody.jsx
  src/components/Post/PostBodyUser/PostBodyUser.jsx
  src/pages/FeedViewPage/FeedViewPage.jsx
Labels: style 💄

#50 ♻ comment 헤더 요소 병합 및 form query code 병합
  src/components/FeedView/Comments/CommentBody/CommentBody.jsx
  src/components/FeedView/Comments/CommentContents/CommentContents.jsx
  src/components/FeedView/Comments/CommentContents/styles.js
  src/components/FeedView/Comments/CommentForm/CommentForm.jsx
  src/components/FeedView/Comments/CommentHeader/CommentHeader.jsx
  src/components/FeedView/Comments/CommentHeader/styles.js
  src/components/FeedView/Comments/ReplyForm/ReplyForm.jsx
  src/components/FeedView/Comments/ReplyForm/styles.js
  src/components/FeedView/index.js
  src/pages/FeedViewPage/FeedViewPage.jsx
Labels: refactor ♻
