Repository sou-so/Souso_Client, pull requests merged in 2022-11, with the labels that each got.

#8 ✨ JoinForm의 input에 fade효과 부여 & 임시로 가입약관 Modal 생성
  src/components/Join/JoinForm/JoinForm.jsx
  src/components/Join/JoinForm/styles.js
  src/components/Join/TermsModal/TermsModal.jsx
  src/components/Join/TermsModal/styles.js
  src/components/Join/index.js
Labels: new feature ✨

#9 ♻ 수정사항 반영 & ✨ 모달 외부클릭시 close기능 추가
  src/components/Join/JoinForm/JoinForm.jsx
  src/components/Join/JoinForm/styles.js
  src/components/Join/TermsModal/TermsModal.jsx
Labels: refactor ♻

#10 💄 AppLayout 및 페이지하단 Navbar UI 추가
  src/App.js
  src/assets/icons/alert.svg
  src/assets/icons/arrow_b.svg
  src/assets/icons/arrow_l.svg
  src/assets/icons/arrow_r.svg
  src/assets/icons/location.svg
  src/components/AppLayout/AppLayout.jsx
  src/components/AppLayout/styles.js
  src/components/Common/Icon/Icon.jsx
  src/components/Common/Navbar/Navbar.jsx
  src/components/Common/Navbar/styles.js
  src/components/Common/PageHeader/PageHeader.jsx
  src/components/Common/PageHeader/styles.js
  src/components/Common/index.js
  src/components/index.js
  src/pages/ChatPage/ChatPage.jsx
  src/pages/FeedPage/FeedPage.jsx
  src/pages/FeedPage/styles.js
  src/pages/MainPage/MainPage.jsx
  src/pages/MeetPage/MeetPage.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/TownAuthPage/TownAuthPage.jsx
  src/pages/index.js
  src/styles/GlobalStyles.js
Labels: style 💄

#11 ✨ 커뮤니티 페이지 UI 생성 & 스크롤 라이브러리 추가
  package-lock.json
  package.json
  src/assets/icons/temp.svg
  src/assets/images/banner_img.png
  src/components/Common/Category/Category.jsx
  src/components/Common/Category/styles.js
  src/components/Common/Icon/Icon.jsx
  src/components/Common/ScrollContainer/ScrollContainer.jsx
  src/components/Common/ScrollContainer/styles.js
  src/components/Common/index.js
  src/components/Feed/FeedBanner/FeedBanner.jsx
  src/components/Feed/FeedBanner/styles.js
  src/components/Feed/FeedHeader/FeedHeader.jsx
  src/components/Feed/FeedHeader/styles.js
  src/components/Feed/HashTags/HashTags.jsx
  src/components/Feed/HashTags/styles.js
  src/components/Feed/PostLatest/PostLatest.jsx
  src/components/Feed/PostLatest/styles.js
  src/components/Feed/PostList/PostList.jsx
  src/components/Feed/PostList/styles.js
  src/components/Feed/PostPopular/PostPopular.jsx
  src/components/Feed/PostPopular/styles.js
  src/components/Feed/SearchBar/SearchBar.jsx
  src/components/Feed/SearchBar/styles.js
  src/components/Feed/index.js
  src/data/posts.json
  src/pages/FeedPage/FeedPage.jsx
  src/pages/FeedPage/styles.js
  src/styles/GlobalStyles.js
  src/styles/Shared.js
Labels: new feature ✨

#12 🚧 post page 구조 형성
  package-lock.json
  package.json
  src/App.js
  src/assets/icons/heart.svg
  src/assets/icons/scrap.svg
  src/components/Common/ProfileImage/ProfileImage.jsx
  src/components/Common/ProfileImage/styles.js
  src/components/Common/ScrollContainer/ScrollContainer.jsx
  src/components/Common/ScrollContainer/styles.js
  src/components/Common/index.js
  src/components/FeedAdd/FeedAdd.jsx
  src/components/FeedAdd/styles.js
  src/components/FeedView/Comments/Comments.jsx
  src/components/FeedView/ImageSlider/ImageSlider.jsx
  src/components/FeedView/ImageSlider/styles.js
  src/components/FeedView/index.js
  src/components/Post/PostBodyUser/PostBodyUser.jsx
  src/components/Post/PostBodyUser/styles.js
  src/components/Post/PostFooterBtn/PostFooterBtn.jsx
  src/components/Post/PostFooterBtn/styles.js
  src/components/Post/index.js
  src/pages/FeedViewPage/FeedViewPage.jsx
  src/pages/FeedViewPage/styles.js
  src/pages/index.js
Labels: new feature ✨

#13 ✨ 게시글 클릭 시 redirect 및 Post 스타일 수정
  src/App.js
  src/assets/icons/comment.svg
  src/components/Common/CategoryTag/CategoryTag.jsx
  src/components/Common/TextClamp/TextClamp.jsx
  src/components/Common/index.js
  src/components/Feed/PostLatest/PostLatest.jsx
  src/components/Feed/PostLatest/styles.js
  src/components/Feed/PostList/PostList.jsx
  src/components/Feed/PostList/styles.js
  src/components/Feed/PostPopular/PostPopular.jsx
  src/components/Feed/PostPopular/styles.js
  src/components/Feed/index.js
  src/components/Post/PostBody/PostBody.jsx
  src/components/Post/PostBody/styles.js
  src/components/Post/PostBodyUser/PostBodyUser.jsx
  src/components/Post/PostBodyUser/styles.js
  src/components/Post/PostFooterBtn/PostFooterBtn.jsx
  src/components/Post/PostFooterBtn/styles.js
  src/components/Post/PostFooterIcon/PostFooterIcon.jsx
  src/components/Post/PostFooterIcon/styles.js
  src/components/Post/Thumbnails/ThumbBottom/ThumbBottom.jsx
  src/components/Post/Thumbnails/ThumbBottom/styles.js
  src/components/Post/Thumbnails/ThumbRight/ThumbRight.jsx
  src/components/Post/Thumbnails/ThumbRight/styles.js
  src/components/Post/index.js
  src/data/posts.json
  src/pages/FeedPage/FeedPage.jsx
  src/pages/FeedViewPage/FeedViewPage.jsx
  src/pages/FeedViewPage/styles.js
  src/styles/GlobalStyles.js
  src/styles/Theme.js
Labels: new feature ✨

#14 ✨ 댓글 구역 기능 구현 & posts.json 파일 업데이트
  src/App.js
  src/assets/icons/airplane.svg
  src/components/FeedView/Comments/CommentBody/CommentBody.jsx
  src/components/FeedView/Comments/CommentBody/styles.js
  src/components/FeedView/Comments/CommentContents/CommentContents.jsx
  src/components/FeedView/Comments/CommentContents/styles.js
  src/components/FeedView/Comments/CommentForm/CommentForm.jsx
  src/components/FeedView/Comments/CommentForm/styles.js
  src/components/FeedView/Comments/Comments.jsx
  src/components/FeedView/ImageSlider/ImageSlider.jsx
  src/components/FeedView/index.js
  src/components/Post/PostFooterBtn/PostFooterBtn.jsx
  src/data/posts.json
  src/pages/FeedViewPage/FeedViewPage.jsx
Labels: new feature ✨

#15 🔥 중복된 route 코드 삭제
  src/App.js
Labels: refactor ♻

#16 💄 마이페이지 UI 추가 (프로필편집, 소소모임 제외)
  package-lock.json
  package.json
  src/App.js
  src/assets/icons/arrow_angle.svg
  src/assets/icons/bin.svg
  src/assets/icons/bookmark_star.svg
  src/assets/icons/dots.svg
  src/assets/icons/pencil.svg
  src/assets/icons/peoples.svg
  src/components/Feed/PostList/PostList.jsx
  src/components/MyPage/ComingMeetup/ComingMeetup.jsx
  src/components/MyPage/ComingMeetup/styles.js
  src/components/MyPage/LinkBox/LinkBox.jsx
  src/components/MyPage/LinkBox/styles.js
  src/components/MyPage/LogoutButton/LogoutButton.jsx
  src/components/MyPage/LogoutButton/styles.js
  src/components/MyPage/UserData/UserData.jsx
  src/components/MyPage/UserData/styles.js
  src/components/MyPage/index.js
  src/components/MySubPage/EditDeleteButton/EditDeleteButton.jsx
  src/components/MySubPage/EditDeleteButton/styles.js
  src/components/MySubPage/MenuTab/MenuTab.jsx
  src/components/MySubPage/MenuTab/styles.js
  src/components/MySubPage/MyComments/MyComments.jsx
  src/components/MySubPage/MyComments/styles.js
  src/components/MySubPage/MyPosts/MyPosts.jsx
  src/components/MySubPage/MyPosts/styles.js
  src/components/MySubPage/SearchButton/SearchButton.jsx
  src/components/MySubPage/SearchButton/styles.js
  src/components/MySubPage/index.js
  src/components/Post/PostFooterIcon/PostFooterIcon.jsx
  src/components/Post/PostFooterIcon/styles.js
  src/components/Post/Thumbnails/ThumbBottom/ThumbBottom.jsx
  src/components/Post/Thumbnails/ThumbBottom/styles.js
  src/components/Post/Thumbnails/ThumbRight/ThumbRight.jsx
  src/components/Post/Thumbnails/ThumbTop/ThumbTop.jsx
  src/components/Post/Thumbnails/ThumbTop/styles.js
  src/components/Post/index.js
  src/data/comingmeets.json
  src/data/myComments.json
  src/data/posts.json
  src/data/user.json
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/styles.js
  src/pages/MyPostPage/MyPostPage.jsx
  src/pages/MyPostPage/styles.js
  src/pages/MyScrapPage/MyScrapPage.jsx
  src/pages/MyScrapPage/styles.js
  src/pages/index.js
  src/styles/GlobalStyles.js
  src/styles/Theme.js
  src/utils/dateConverter.js
Labels: style 💄

#17 ✨ React-Query로 회원가입 제출 & 닉네임 중복체크 구현 / useForm Hooks 추가
  package-lock.json
  package.json
  src/components/Common/ScrollContainer/styles.js
  src/components/Join/Input/Input.jsx
  src/components/Join/Input/styles.js
  src/components/Join/InputDuplicated/InputDuplicated.jsx
  src/components/Join/InputVerified/InputVerified.jsx
  src/components/Join/JoinForm/JoinForm.jsx
  src/components/Join/JoinForm/styles.js
  src/components/Join/TermsButton/TermsButton.jsx
  src/components/Join/TermsButton/styles.js
  src/components/Join/index.js
  src/components/TownAuth/SearchBar/styles.js
  src/hooks/useForm.js
  src/index.js
  src/pages/JoinPage/JoinPage.jsx
  src/pages/JoinPage/styles.js
  src/styles/Shared.js
  src/styles/Theme.js
  src/utils/api/_ep.js
  src/utils/api/categoryAPI.js
  src/utils/api/joinAPI.js
  src/utils/valid_join.js
Labels: new feature ✨

#21 💄 마이페이지 프로필 편집 & 나의 소소모임 페이지 UI 작성
  src/App.js
  src/assets/icons/camera.svg
  src/assets/icons/gps.svg
  src/assets/images/default_profile.jpg
  src/components/Common/MenuTab/MenuTab.jsx
  src/components/Common/MenuTab/styles.js
  src/components/Common/ProfileImage/ProfileImage.jsx
  src/components/Common/TextClamp/TextClamp.jsx
  src/components/Common/index.js
  src/components/Join/InputBirthDate/InputBirthDate.jsx
  src/components/Join/InputBirthDate/styles.js
  src/components/Join/index.js
  src/components/MyPage/ComingMeetup/ComingMeetup.jsx
  src/components/MyPage/ComingMeetup/styles.js
  src/components/MyPage/UserData/UserData.jsx
  src/components/MySubPage/MyMeets/MyMeets.jsx
  src/components/MySubPage/MyMeets/styles.js
  src/components/MySubPage/index.js
  src/components/ProfileEdit/EditImage/EditImage.jsx
  src/components/ProfileEdit/EditImage/styles.js
  src/components/ProfileEdit/ProfileForm/ProfileForm.jsx
  src/components/ProfileEdit/ProfileForm/styles.js
  src/components/ProfileEdit/index.js
  src/data/comingmeets.json
  src/data/mymeets.json
  src/data/user.json
  src/pages/MyMeetPage/MyMeetPage.jsx
  src/pages/MyMeetPage/styles.js
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/styles.js
  src/pages/MyPostPage/MyPostPage.jsx
  src/pages/MyScrapPage/MyScrapPage.jsx
  src/pages/ProfileEditPage/ProfileEditPage.jsx
  src/pages/ProfileEditPage/styles.js
  src/pages/index.js
  src/styles/Theme.js
  src/utils/dateConverter.js
  src/utils/monthDivider.js
Labels: new feature ✨

#22 ✨ Feed Add Page 구성 및 categoryAPI 연결
  src/assets/icons/camera.svg
  src/assets/icons/question_mark.svg
  src/components/FeedAdd/CategorySelect/CategorySelect.jsx
  src/components/FeedAdd/CategorySelect/styles.js
  src/components/FeedAdd/FeedAdd.jsx
  src/components/FeedAdd/FeedForm/FeedForm.jsx
  src/components/FeedAdd/FeedForm/styles.js
  src/components/FeedAdd/ImgAddPreview/ImgAddPreview.jsx
  src/components/FeedAdd/ImgAddPreview/styles.js
  src/components/FeedAdd/SelectedCategory/SelectedCategory.jsx
  src/components/FeedAdd/SelectedCategory/styles.js
  src/components/FeedAdd/index.js
  src/pages/FeedAddPage/FeedAddPage.jsx
  src/pages/FeedAddPage/styles.js
  src/pages/FeedViewPage/styles.js
  src/styles/GlobalStyles.js
Labels: new feature ✨

#23 ✨ 프로필 정보 & 회원탈퇴 API 연결
  src/api/endpoints/index.js
  src/api/index.js
  src/api/interceptor.js
  src/api/queries/category.js
  src/api/queries/join.js
  src/api/queries/user.js
  src/components/Common/Category/Category.jsx
  src/components/Feed/FeedBanner/FeedBanner.jsx
  src/components/Join/InputBirthDate/InputBirthDate.jsx
  src/components/Join/InputDuplicated/InputDuplicated.jsx
  src/components/MyPage/LogoutButton/LogoutButton.jsx
  src/components/MyPage/UserData/UserData.jsx
  src/components/MyPage/UserData/styles.js
  src/data/user.json
  src/pages/FeedAddPage/FeedAddPage.jsx
  src/pages/JoinPage/JoinPage.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/ProfileEditPage/styles.js
  src/utils/api/_axios.js
  src/utils/api/_ep.js
  src/utils/api/categoryAPI.js
  src/utils/api/joinAPI.js
  src/utils/api/userAPI.js
  src/utils/authToken.js
  src/utils/dateConverter.js
Labels: new feature ✨

#24 ♻ 게시글 추가 카테고리 버튼 컴포넌트 수정
  src/api/endpoints/index.js
  src/api/index.js
  src/api/queries/feed.js
  src/components/AppLayout/AppLayout.jsx
  src/components/Common/Category/Category.jsx
  src/components/Common/Category/styles.js
  src/components/FeedAdd/CategorySelect/CategorySelect.jsx
  src/components/FeedAdd/CategorySelect/styles.js
  src/components/FeedAdd/FeedForm/FeedForm.jsx
  src/components/FeedAdd/FeedForm/styles.js
  src/components/FeedAdd/SelectedCategory/SelectedCategory.jsx
  src/components/FeedAdd/index.js
  src/pages/FeedAddPage/FeedAddPage.jsx
Labels: refactor ♻

#25 ✨ 휴대폰 인증 API 연결 & FeedAddPage의 CategoryModal 수정
  src/api/endpoints/index.js
  src/api/queries/join.js
  src/components/FeedAdd/CategoryModal/CategoryModal.jsx
  src/components/FeedAdd/CategoryModal/styles.js
  src/components/FeedAdd/FeedForm/FeedForm.jsx
  src/components/FeedAdd/SelectedCategory/SelectedCategory.jsx
  src/components/FeedAdd/SelectedCategory/styles.js
  src/components/FeedAdd/index.js
  src/components/Join/InputVerified/InputVerified.jsx
  src/pages/FeedAddPage/FeedAddPage.jsx
Labels: new feature ✨

#26 ✨ Feed 게시글 추가 API 연결 & 이미지 미리보기 슬라이드 구현
  src/components/Common/ScrollHorizon/ScrollHorizon.js
  src/components/Common/index.js
  src/components/Feed/HashTags/HashTags.jsx
  src/components/FeedAdd/FeedForm/FeedForm.jsx
  src/components/FeedAdd/FeedForm/styles.js
  src/components/FeedAdd/ImgAddPreview/ImgAddPreview.jsx
  src/components/FeedAdd/ImgAddPreview/styles.js
  src/pages/FeedAddPage/FeedAddPage.jsx
  src/pages/FeedAddPage/styles.js
  src/pages/MyMeetPage/MyMeetPage.jsx
  src/pages/MyMeetPage/styles.js
Labels: new feature ✨

#27 ♻ Navbar 아이콘 변경 & 게시글 목록 GET 요청에 맞게 변수명 수정
  src/api/endpoints/index.js
  src/api/queries/feed.js
  src/assets/icons/nav/nav1.svg
  src/assets/icons/nav/nav2.svg
  src/assets/icons/nav/nav3.svg
  src/assets/icons/nav/nav4.svg
  src/components/Common/Navbar/Navbar.jsx
  src/components/Common/Navbar/styles.js
  src/components/Feed/PostList/PostList.jsx
  src/components/Post/PostBody/PostBody.jsx
  src/components/Post/PostBody/styles.js
  src/components/Post/PostBodyUser/PostBodyUser.jsx
  src/components/Post/PostBodyUser/styles.js
  src/components/Post/PostFooterBtn/PostFooterBtn.jsx
  src/components/Post/PostFooterIcon/PostFooterIcon.jsx
  src/components/Post/Thumbnails/ThumbBottom/ThumbBottom.jsx
  src/components/Post/Thumbnails/ThumbRight/ThumbRight.jsx
  src/styles/Theme.js
Labels: refactor ♻

#28 ✨ 북마크 추가/삭제 API 연결 및 카테고리별 Feed 페이지 추가
  src/App.js
  src/api/endpoints/index.js
  src/api/queries/feed.js
  src/assets/icons/bookmark.svg
  src/assets/icons/heart.svg
  src/components/Common/Category/Category.jsx
  src/components/Feed/PostList/PostList.jsx
  src/components/Post/PostBodyUser/PostBodyUser.jsx
  src/components/Post/PostFooterBtn/PostFooterBtn.jsx
  src/components/Post/PostFooterBtn/styles.js
  src/components/Post/PostFooterIcon/PostFooterIcon.jsx
  src/components/Post/Thumbnails/ThumbBottom/ThumbBottom.jsx
  src/pages/FeedListPage/FeedListPage.jsx
  src/pages/FeedListPage/styles.js
  src/pages/FeedPage/FeedPage.jsx
  src/pages/FeedViewPage/FeedViewPage.jsx
  src/pages/index.js
  src/styles/Theme.js
Labels: new feature ✨

#29 ✨ Feed 상세페이지 API 연결
  src/api/endpoints/index.js
  src/api/queries/feed.js
  src/components/FeedView/Comments/CommentBody/CommentBody.jsx
  src/components/FeedView/Comments/CommentContents/CommentContents.jsx
  src/components/FeedView/Comments/CommentForm/CommentForm.jsx
  src/components/FeedView/ImageSlider/ImageSlider.jsx
  src/components/FeedView/ImageSlider/styles.js
  src/pages/FeedViewPage/FeedViewPage.jsx
Labels: new feature ✨

#30 ✨ 게시글 좋아요 기능 API 연결
  src/api/endpoints/index.js
  src/api/queries/feed.js
  src/components/Post/PostFooterBtn/PostFooterBtn.jsx
  src/components/Post/PostFooterBtn/styles.js
  src/components/Post/PostFooterIcon/PostFooterIcon.jsx
  src/components/Post/PostFooterIcon/styles.js
  src/components/Post/Thumbnails/ThumbBottom/ThumbBottom.jsx
  src/pages/FeedViewPage/FeedViewPage.jsx
Labels: new feature ✨

#31 ✨ useInfiniteQuery를 사용한 게시글 무한 스크롤 구현
  package-lock.json
  package.json
  src/api/endpoints/index.js
  src/api/queries/category.js
  src/assets/images/loading.gif
  src/components/Common/Category/Category.jsx
  src/components/Feed/PostList/PostList.jsx
  src/components/Feed/PostList/styles.js
  src/components/Post/PostBodyUser/PostBodyUser.jsx
  src/hooks/useObserver.js
  src/pages/FeedListPage/FeedListPage.jsx
  src/pages/FeedPage/FeedPage.jsx
  src/pages/FeedPage/styles.js
Labels: new feature ✨

#32 ✨ 댓글 목록 조회 및 댓글 추가 API 연결
  src/api/endpoints/index.js
  src/api/queries/comment.js
  src/api/queries/feed.js
  src/components/FeedView/Comments/CommentBody/CommentBody.jsx
  src/components/FeedView/Comments/CommentBody/styles.js
  src/components/FeedView/Comments/CommentContents/CommentContents.jsx
  src/components/FeedView/Comments/CommentContents/styles.js
  src/components/FeedView/Comments/CommentForm/CommentForm.jsx
  src/components/Post/PostFooterBtn/PostFooterBtn.jsx
  src/components/Post/PostFooterIcon/PostFooterIcon.jsx
  src/pages/FeedViewPage/FeedViewPage.jsx
Labels: new feature ✨
